services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    volumes:
      - ./backend:/app
  
  streamlit:
    build: ./backend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    volumes:
      - ./backend:/app
    command: streamlit run streamlit_app/dashboard.py --server.port=8501 --server.address=0.0.0.0

volumes:
  qdrant_data: