from setuptools import setup, find_packages

setup(
    name="revenue-leakage-detection",
    version="0.1.0",
    description="A Revenue Leakage Detection System using CrewAI + Qdrant with Gemini as LLM",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(where="backend"),
    package_dir={"": "backend"},
    install_requires=[
        "crewai",
        "qdrant-client",
        "google-generativeai",
        "fastapi",
        "uvicorn",
        "pydantic",
        "python-dotenv",
        "typer",
        "streamlit",
        "plotly",
        "fpdf2",
        "pymupdf",
        "pytesseract",
        "pillow",
        "langchain-google-genai",
        "opencv-python-headless",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)